### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by napoleo** [GospelPlan/Gospel-docs-issues#1]
* 操作系统: ubuntu.
* 浏览器及浏览器版本: mozilla 
* 出现的问题：
1.编辑器无法使用点我，刷新之前提示用户将丢失信息，重新加载
2.样式的一些问题：右边栏放大后文字溢出，IDE 缩小浏览器后部分功能无法看到，没有滚动条，没有响应式。
3.上传文件，点击或拖拽上传，没有反馈（上传成功）我还以为是没反应呢
4.在左边栏的 caret 上不断单击，右边的文字左右跳动，一个蓝色的图标闪一下消失
5.点击最上方工具栏，只要是弹出对话框，则最左边和最右边的两个工具栏的文字都被挤成一半。缩小再放大就又正常了
6.PLAIN_TEXT 没有用？？应该是点哪个，哪个就出现在那个位置吧
7.微信小程序，头标题，中文比英文和数字的颜色暗（或浅 取决于头字体是black 还是white)
快速部署里面表单的label字的颜色不一样，有深有浅
* 操作流程：

## 界面截图（可选）

**Comment by 549781430** [comment]
* 操作系统: windows
* 浏览器及浏览器版本: Google Chrome
* 出现的问题：
1、控件宽度设置100%后也无法占满界面。
2、创建微信小程序后，使用九宫格控件，点击单个格子后其他格子会被挤下去，布局错乱。
3、使用空白分割线后，混动鼠标，会覆盖在其他控件上。
4、表单控件中的验证码输入框会被图片覆盖一部分
5、拖动控件往上放时，有时候控件会跑到最下面去。
6、创建应用后进入快速部署，立即创建无法点击。

**Comment by leinue** [comment]
@549781430 第六条是因为目前有资源创建限制，每个人只能创建一个快速部署应用

**Comment by leinue** [comment]
@549781430 
回复：
第一条：请确认是否拉到了头部，头部是有padding的
第四条：不太明白意思，验证码输入框最右边默认是有 图片的
第六条：目前有资源创建限制，你应该已经创建过一次带docker的应用了

**Comment by leinue** [comment]
@napoleo 
回复：
第四条：我们没测到
第七条：这个应该和浏览器渲染有关

firefox下有些样式不太兼容

**Comment by leinue** [comment]
待解决问题：

napoleo
1 2 3 5 6

549781430
2 3 5
