### ISSUE TITLE
进入ide新建项目，web项目出错

### ISSUE THREAD

**Issue by githubxt** [GospelPlan/Gospel-docs-issues#12]
* 操作系统: win10
* 浏览器及浏览器版本: 谷歌版本 55.0.2883.87 m
* 出现的问题：创建项目出错
* 操作流程：进入ide-->新建项目-->具体看截图，然后就回到了新建项目的首页

## 界面截图（可选）
![1](https://cloud.githubusercontent.com/assets/20595507/23330484/ceeca6bc-fb89-11e6-8d9c-1b83a2465e2d.png)
![2](https://cloud.githubusercontent.com/assets/20595507/23330481/ceea25fe-fb89-11e6-8d9d-9136992510fc.png)
![3](https://cloud.githubusercontent.com/assets/20595507/23330482/ceeab852-fb89-11e6-9113-ce98b6c3939b.png)
![4](https://cloud.githubusercontent.com/assets/20595507/23330483/ceeb29cc-fb89-11e6-8efd-be73f4af0241.png)

**Comment by leinue** [comment]
新版本已修复
