### ISSUE TITLE
创建第二个项目，选的可视化，创建出错

### ISSUE THREAD

**Issue by githubxt** [GospelPlan/Gospel-docs-issues#14]
* 操作系统: win10
* 浏览器及浏览器版本:  谷歌
* 出现的问题：如题
* 操作流程：创建第二个项目，选的可视化，创建出错

## 界面截图（可选）
![1](https://cloud.githubusercontent.com/assets/20595507/23351807/60e4e6e0-fcfe-11e6-9a77-cd2e58a10a1e.PNG)

**Comment by leinue** [comment]
新版本已修复
